# fly.toml app configuration file generated for linkblocks on 2024-02-26T11:23:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linkblocks'
primary_region = 'ams'

[env]
  ADMIN_USERNAME = 'rafael'
  LISTEN = '0.0.0.0:8080'
  RUST_LOG='debug'
  BASE_URL='linkblocks.fly.dev'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
